VHAINNOVATIONS/ASRCM

srcalc/src/main/java/gov/va/med/srcalc/web/controller/CalculationController.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/EnterVariablesController.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/InputParserVisitor.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/VariableEntry.java, srcalc/src/main/webapp/js/enterVariables.js, srcalc/src/test/java/gov/va/med/srcalc/domain/SampleObjects.java, srcalc/src/test/java/gov/va/med/srcalc/web/controller/CalculationControllerIT.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/InputParserVisitorTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/VariableEntryTest.java
This is actually some testing feedback from Bill: initially select discrete Numerical radios and tie the numerical text boxes to the radio buttons.
=> ASRC-15: Serum Albumin Lab Result Translation

srcalc/src/main/java/gov/va/med/srcalc/domain/variable/DiscreteNumericalVariable.java, srcalc/src/test/java/gov/va/med/srcalc/domain/variable/DiscreteNumericalVariableTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/variable/NumericalRangeTest.java, srcalc/src/test/java/gov/va/med/srcalc/test/util/TestHelpers.java
=> Within Normal Limits (WNL) should now sort to the front of the category

srcalc/src/main/java/gov/va/med/srcalc/web/controller/ReferenceDataController.java, srcalc/src/main/resources/srcalc-controller.xml, srcalc/src/main/webapp/WEB-INF/web.xml, srcalc/src/main/webapp/js/enterVariables.js, srcalc/src/test/java/gov/va/med/srcalc/web/controller/CalculationControllerIT.java
1. Eliminate caching of actual pages.
2. Force the browser to check for new versions of resources.
=> Fix ASRC-244: User's browser may use stale files

install/resources/create_database.sql, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/AbstractNumericalVariable.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/ValueTooHighException.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/ValueTooLowException.java, srcalc/src/main/resources/messages.properties, srcalc/src/test/java/gov/va/med/srcalc/domain/variable/DiscreteNumericalValueTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/variable/NumericalValueTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/InputParserVisitorTest.java, srcalc/src/test/resources/sql/insert_base_data.sql
so that they can be inclusive or exclusive. Error codes and exceptions are updated.
=> Asrc 243 - Adding a range to all numerical variables

install/resources/create_database.sql, srcalc/src/main/java/gov/va/med/srcalc/domain/Patient.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/AbstractVariable.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/Variable.java, srcalc/src/main/java/gov/va/med/srcalc/vista/RpcVistaPatientDao.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/EnterVariablesController.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/VariableEntry.java, srcalc/src/test/java/gov/va/med/srcalc/domain/CalculationTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/SampleObjects.java, srcalc/src/test/java/gov/va/med/srcalc/service/CalculationServiceIT.java, srcalc/src/test/java/gov/va/med/srcalc/vista/MockVistaPatientDao.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/VariableEntryTest.java, srcalc/src/test/resources/sql/insert_base_data.sql
field on the enter variables page. Gender is stored, but not used.
=> ASRC-19: Added patient age and gender. Age is now placed into the numerical input

srcalc/src/main/java/gov/va/med/srcalc/domain/Patient.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/DerivedTerm.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/AbstractVariable.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/Variable.java, srcalc/src/main/java/gov/va/med/srcalc/vista/RemoteProcedure.java, srcalc/src/main/java/gov/va/med/srcalc/vista/RpcVistaPatientDao.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/VariableEntry.java, srcalc/src/main/webapp/WEB-INF/views/enterVariables.jsp, srcalc/src/test/java/gov/va/med/srcalc/domain/SampleObjects.java, srcalc/src/test/java/gov/va/med/srcalc/vista/RpcVistaPatientDaoTest.java
retrieved from VistA and displayed on the variable entry page. The dates
on which the data were measured are also displayed on the variable entry
page.
=> Patient BMI, height, weight, and weight 6 months ago are now being

srcalc/src/main/java/gov/va/med/srcalc/util/RetrievalEnum.java, srcalc/src/main/java/gov/va/med/srcalc/vista/RpcVistaPatientDao.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/VariableEntry.java
Changed the date range for "weight 6 months ago" from 3-12 months prior
to the most recent weight measurement, to 6-12 months prior to the most
recent weight measurement.
=> ASRC-26 Refactoring to remove the switch statement for automatic retrieval.

srcalc/src/main/webapp/WEB-INF/views/displayResults.jsp, srcalc/src/main/webapp/WEB-INF/views/enterVariables.jsp, srcalc/src/main/webapp/WEB-INF/views/selectSpecialty.jsp, srcalc/src/main/webapp/css/srcalc.css
=> ASRC-210 Fixing redirect links to look like standard buttons so that the site is

srcalc/src/main/webapp/WEB-INF/views/enterVariables.jsp, srcalc/src/main/webapp/js/enterVariables.js
Create a module with its own scope for enterVariables.js instead of a
disorganized assortment of globals and closures.
=> ASRC-261: Refactor enterVariables.js

srcalc/src/main/webapp/WEB-INF/views/enterVariables.jsp, srcalc/src/main/webapp/css/srcalc.css, srcalc/src/main/webapp/js/enterVariables.js
This improves performance slightly on modern browsers but drastically on IE8.
=> ASRC-260: lazy-init procedure select table

srcalc/src/main/java/gov/va/med/srcalc/domain/Calculation.java, srcalc/src/main/webapp/WEB-INF/views/displayResults.jsp, srcalc/src/main/webapp/WEB-INF/views/enterVariables.jsp, srcalc/src/main/webapp/css/srcalc.css
calculation workflow. The "Start New Calculation" buttons are now links.
=> Moved the positioning of buttons to better reflect the progress of the

srcalc/src/main/webapp/WEB-INF/views/enterVariables.jsp, srcalc/src/main/webapp/css/srcalc.css
=> Colors alternate for variable inputs. Removed "Numerical:" text from

srcalc/build.gradle, srcalc/src/main/java/gov/va/med/srcalc/vista/RpcVistaPatientDao.java, srcalc/src/main/java/gov/va/med/srcalc/vista/VistaPatientDao.java
=> The information saved to the TIU note now wraps the lines in the note at

srcalc/build.gradle
=> Changed the version of Apache Commons from 3.4 to 3.3.2 to comply with

srcalc/src/main/java/gov/va/med/srcalc/db/package-info.java, srcalc/src/main/java/gov/va/med/srcalc/domain/Procedure.java, srcalc/src/main/java/gov/va/med/srcalc/domain/Specialty.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/RiskModel.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/Rule.java, srcalc/src/main/java/gov/va/med/srcalc/domain/package-info.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/AbstractNumericalVariable.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/BooleanVariable.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/DiscreteNumericalVariable.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/NumericalVariable.java, srcalc/src/main/java/gov/va/med/srcalc/domain/variable/ProcedureVariable.java, srcalc/src/main/java/gov/va/med/srcalc/service/AdminService.java, srcalc/src/main/java/gov/va/med/srcalc/service/CalculationService.java, srcalc/src/main/java/gov/va/med/srcalc/service/DefaultCalculationService.java, srcalc/src/main/java/gov/va/med/srcalc/service/EditVariable.java, srcalc/src/main/java/gov/va/med/srcalc/service/package-info.java, srcalc/src/main/java/gov/va/med/srcalc/vista/RpcVistaPatientDao.java, srcalc/src/main/java/gov/va/med/srcalc/vista/VistaPatientDao.java, srcalc/src/main/java/gov/va/med/srcalc/vista/package-info.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/DisplayResultsController.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/EditVariableController.java, srcalc/src/main/java/gov/va/med/srcalc/web/package-info.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/VariableEntry.java, srcalc/src/test/java/gov/va/med/srcalc/vista/MockVistaPatientDao.java, srcalc/src/test/java/gov/va/med/srcalc/vista/RpcVistaPatientDaoTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/controller/CalculationControllerIT.java
This is mostly expanding the package Javadocs, but also eliminates many small warnings when generating the Javadoc HTML pages.
=> Javadocs update

srcalc/src/main/java/gov/va/med/srcalc/service/package-info.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/AdminHomeController.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/EditVariableController.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/EditVariable.java, srcalc/src/test/java/gov/va/med/srcalc/web/controller/EditVariableControllerIT.java
and some Javadocs.
Note: this does not contain the display name character validation, which I'll do after we discuss on scrum.
=> ASRC-141 Part 4: Fix a broken redirect

srcalc/src/main/java/gov/va/med/srcalc/domain/model/DerivedTerm.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/Rule.java, srcalc/src/main/java/gov/va/med/srcalc/service/DefaultCalculationService.java, srcalc/src/test/java/gov/va/med/srcalc/domain/model/DerivedTermTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/model/RuleTest.java, srcalc/src/test/java/gov/va/med/srcalc/service/DefaultCalculationServiceTest.java
I also improved `DerivedTerm.toString()` based on my experience debugging yesterday.
=> ASRC-51 #3: don't save risk upon invalid signature

srcalc/src/main/java/gov/va/med/srcalc/domain/model/VariableGroup.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/ValueDisplayOrder.java
=> Procedures are sorted to the of top display results page based off of

srcalc/src/main/java/gov/va/med/srcalc/domain/calculation/CalculationResult.java, srcalc/src/test/java/gov/va/med/srcalc/domain/calculation/CalculationResultTest.java
Group to be placed immediately under the procedure value (if there is
one) in the TIU note body.
=> ASRC-265 Small refactorings and reordered any values/variables in the Procedure

srcalc/src/main/java/gov/va/med/srcalc/web/controller/CalculationController.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/SrcalcSession.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/Views.java, srcalc/src/main/webapp/WEB-INF/views/confirmNewCalc.jsp, srcalc/src/main/webapp/WEB-INF/views/displayResults.jsp, srcalc/src/main/webapp/WEB-INF/views/enterVariables.jsp, srcalc/src/test/java/gov/va/med/srcalc/web/controller/CalculationControllerIT.java
=> ASRC-236 The user will now be warned about overwriting an in-progress

srcalc/src/main/webapp/js/displayResults.js
=> ASRC-284 The error message is now properly cleared after using an invalid

srcalc/src/main/webapp/WEB-INF/views/confirmNewCalc.jsp
starting new one for a different patient.
=> ASRC-236 Added an alert to the user about old calculations being invalid when

srcalc/src/main/java/gov/va/med/srcalc/domain/calculation/ValueRetriever.java, srcalc/src/main/java/gov/va/med/srcalc/vista/VistaLabs.java
=> ASRC-63 Added Creatinine, Alkaline Phosphatase, BUN, and SGOT for automatic

srcalc/src/main/java/gov/va/med/srcalc/domain/calculation/ValueRetriever.java, srcalc/src/main/java/gov/va/med/srcalc/vista/VistaLabs.java
=> ASRC-64 Added lab retrieval for WBC, platelets, hematocrit, sodium, INR,

install/resources/create_database.sql, srcalc/src/main/java/gov/va/med/srcalc/domain/model/DiscreteNumericalVariable.java, srcalc/src/main/webapp/WEB-INF/views/enterVariables.jsp, srcalc/src/test/java/gov/va/med/srcalc/domain/calculation/DiscreteNumericalValueTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/model/DiscreteNumericalVariableTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/model/SampleModels.java, srcalc/src/test/java/gov/va/med/srcalc/test/util/TestHelpers.java, srcalc/src/test/java/gov/va/med/srcalc/web/DynamicValueVisitorTest.java, srcalc/src/test/resources/sql/insert_base_data.sql
Infer a Category's lower bound. This eliminates redundant Category configuration.
=> ASRC-230: improve category ordering

srcalc/src/main/java/gov/va/med/srcalc/domain/calculation/ValueRetriever.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/AbstractNumericalVariable.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/DiscreteNumericalVariable.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/NumericalRange.java, srcalc/src/main/java/gov/va/med/srcalc/service/DefaultAdminService.java, srcalc/src/main/java/gov/va/med/srcalc/util/ValidationCodes.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/admin/NewDiscreteNumericalVarController.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/Views.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/admin/CategoryBuilder.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/admin/EditAbstractNumericalVar.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/admin/EditDiscreteNumericalVar.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/admin/EditDiscreteNumericalVarValidator.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/admin/NumericalRangeBuilder.java, srcalc/src/main/resources/messages.properties, srcalc/src/main/webapp/WEB-INF/tags/editVariablePage.tag, srcalc/src/main/webapp/WEB-INF/views/adminHome.jsp, srcalc/src/main/webapp/WEB-INF/views/fragments/discreteNumericalProperties.jspf, srcalc/src/main/webapp/WEB-INF/views/newDiscreteNumericalVariable.jsp, srcalc/src/main/webapp/css/srcalc.css, srcalc/src/main/webapp/js/editVariable.js, srcalc/src/test/java/gov/va/med/srcalc/domain/model/NumericalVariableTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/model/RuleTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/controller/admin/NewVarControllerIT.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/admin/CategoryBuilderTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/admin/EditBaseVarValidatorTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/admin/EditDiscreteNumericalVarTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/admin/EditDiscreteNumericalVarValidatorTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/admin/EditMultiSelectVarTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/admin/EditMultiSelectVarValidatorTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/admin/NumericalRangeBuilderTest.java
I want to update the edit MultiSelectVariable view based on the improvements I made here, but I'll do that in a separate PR. I wanted to get this one out.
=> ASRC-230: support creating a new DiscreteNumericalVariable

srcalc/src/main/java/gov/va/med/srcalc/domain/calculation/ValueRetriever.java, srcalc/src/main/java/gov/va/med/srcalc/vista/RpcVistaPatientDao.java, srcalc/src/main/java/gov/va/med/srcalc/vista/vistalink/VistaLinkProcedureCaller.java, srcalc/src/main/java/gov/va/med/srcalc/web/DynamicValueVisitor.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/EnterVariablesController.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/InputParserVisitor.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/VariableEntry.java, srcalc/src/test/java/gov/va/med/srcalc/domain/calculation/SampleCalculations.java, srcalc/src/test/java/gov/va/med/srcalc/domain/model/SampleModels.java, srcalc/src/test/java/gov/va/med/srcalc/vista/RpcVistaPatientDaoTest.java, srcalc/src/test/java/gov/va/med/srcalc/vista/vistalink/MockVistaLinkConnection.java, srcalc/src/test/java/gov/va/med/srcalc/web/controller/CalculationControllerIT.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/InputParserVisitorTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/VariableEntryTest.java
tests for retrieved labs. Refactored to use Splitter instead of java's
split() method for splitting strings.
=> ASRC-68: Fixed an error when no units are present in a retrieved lab value. Added

srcalc/src/main/webapp/css/srcalc.css, srcalc/src/main/webapp/js/enterVariables.js
new text inputs account for this ability.
=> Added the ability to search for words in the procedure description. Two

srcalc/src/main/webapp/js/enterVariables.js
storing the text before the draw method and then reapplying it after.
=> ASRC-8 Overriding the default behavior of datatables' draw() method by

srcalc/src/main/webapp/js/editVariable.js
Fixing text boxes not being the same size for adding and editing Radio Button type variables.
=> Asrc text box fix

install/resources/create_database.sql, srcalc/src/main/java/gov/va/med/srcalc/db/ProcedureDao.java, srcalc/src/main/java/gov/va/med/srcalc/db/ProcedureLoaderVisitor.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/Procedure.java, srcalc/src/main/java/gov/va/med/srcalc/service/DefaultReferenceDataService.java, srcalc/src/main/java/gov/va/med/srcalc/service/ReferenceDataService.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/ReferenceDataController.java, srcalc/src/main/java/gov/va/med/srcalc/web/controller/admin/AdminHomeController.java, srcalc/src/test/java/gov/va/med/srcalc/web/controller/CalculationControllerIT.java, srcalc/src/test/java/gov/va/med/srcalc/web/controller/admin/AdminHomeControllerIT.java, srcalc/src/test/java/gov/va/med/srcalc/web/controller/admin/EditVariableControllerIT.java, srcalc/src/test/java/gov/va/med/srcalc/web/controller/admin/NewVarControllerIT.java, srcalc/src/test/resources/hibernate.properties, srcalc/src/test/resources/sql/dummy_procedures.sql, srcalc/src/test/resources/sql/insert_dummy_models.sql
I also moved AdminHomeController to the `admin` sub-package where it belongs.
=> ASRC-10 #1: Add "eligible" attribute to Procedures

srcalc/src/main/webapp/WEB-INF/views/editProcedures.jsp, srcalc/src/main/webapp/css/srcalc.css
Also improve the disabled button appearance.
=> ASRC-10: fix procedure form in IE8

srcalc/src/main/webapp/WEB-INF/views/editRule.jsp
Add a warning message on the UI for attempting to add too many matchers (values) in a rule.
=> ASRC-5: Warning message for max matchers.

srcalc/src/main/java/gov/va/med/srcalc/domain/calculation/Calculation.java, srcalc/src/main/java/gov/va/med/srcalc/domain/calculation/CalculationResult.java, srcalc/src/main/java/gov/va/med/srcalc/domain/calculation/SignedResult.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/BooleanTerm.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/ConstantTerm.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/DerivedTerm.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/DiscreteTerm.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/ModelTerm.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/NumericalTerm.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/ProcedureTerm.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/RiskModel.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/Rule.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/SingleVariableTerm.java, srcalc/src/main/java/gov/va/med/srcalc/vista/RpcVistaSurgeryDao.java, srcalc/src/test/java/gov/va/med/srcalc/domain/calculation/CalculationResultTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/calculation/CalculationTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/calculation/SignedResultTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/model/RuleTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/model/SampleModels.java, srcalc/src/test/java/gov/va/med/srcalc/service/CalculationServiceIT.java, srcalc/src/test/java/gov/va/med/srcalc/vista/RpcVistaSurgeryDaoTest.java, srcalc/src/test/resources/sql/insert_dummy_models.sql
Risk Calculation results were previously using doubles, but we don't need that kind of
precision.
=> ASRC-52: using floats throughout the app

install/resources/create_database.sql, install/resources/schema_upgrade_0_10.sql
Also add a schema upgrade script here since it contains no VA-internal data.
=> ASRC-4 fix: update schema

srcalc/src/main/java/gov/va/med/srcalc/domain/calculation/DiscreteNumericalValue.java, srcalc/src/main/java/gov/va/med/srcalc/domain/model/ValueMatcher.java, srcalc/src/main/java/gov/va/med/srcalc/web/DynamicValueVisitor.java, srcalc/src/test/java/gov/va/med/srcalc/domain/model/ValueMatcherTest.java
This allows comparison in rules.
=> ASRC-299: make DiscreteNumericalValue.getValue() return a String

srcalc/src/main/java/gov/va/med/srcalc/db/HistoricalSearchParameters.java, srcalc/src/main/webapp/WEB-INF/views/admin/summaryReportResults.jsp, srcalc/src/main/webapp/WEB-INF/views/admin/utilizationReportResults.jsp, srcalc/src/main/webapp/css/srcalc.css, srcalc/src/test/java/gov/va/med/srcalc/db/HistoricalSearchParametersTest.java
and put divider lines between the rows.
=> ASRC-59: add applied parameters to the report

srcalc/src/main/java/gov/va/med/srcalc/domain/model/Specialty.java, srcalc/src/main/webapp/css/srcalc.css, srcalc/src/test/java/gov/va/med/srcalc/domain/SpecialtyTest.java, srcalc/src/test/java/gov/va/med/srcalc/domain/model/SampleModels.java, srcalc/src/test/resources/sql/insert_dummy_models.sql
Some small improvements in preparation for the greater improvements to make for ASRC-46. I just split these out to make reviewing easier.
=> ASRC-46 minor refactoring

srcalc/src/main/java/gov/va/med/srcalc/domain/Patient.java, srcalc/src/main/java/gov/va/med/srcalc/domain/calculation/ValueRetriever.java, srcalc/src/main/java/gov/va/med/srcalc/vista/RpcVistaPatientDao.java, srcalc/src/main/java/gov/va/med/srcalc/web/view/VariableEntry.java, srcalc/src/test/java/gov/va/med/srcalc/domain/calculation/SampleCalculations.java, srcalc/src/test/java/gov/va/med/srcalc/domain/calculation/ValueRetrieverTest.java, srcalc/src/test/java/gov/va/med/srcalc/vista/RpcVistaPatientDaoTest.java, srcalc/src/test/java/gov/va/med/srcalc/web/view/VariableEntryTest.java
It was simpler to refactor Patient a bit than to document it in its current state.
I also added tests for almost all ValueRetrievers and simplified the ValueRetriever implementations.
=> ASRC-319: preliminary refactoring

srcalc/src/main/java/gov/va/med/srcalc/security/AccessVerifyAuthenticationProvider.java, srcalc/src/main/java/gov/va/med/srcalc/security/CcowTokenAuthenticationProvider.java, srcalc/src/main/java/gov/va/med/srcalc/vista/RemoteProcedure.java, srcalc/src/main/java/gov/va/med/srcalc/vista/RpcVistaPatientDao.java, srcalc/src/main/java/gov/va/med/srcalc/vista/VistaAuthenticator.java, srcalc/src/main/java/gov/va/med/srcalc/vista/VistaProcedureCaller.java, srcalc/src/main/java/gov/va/med/srcalc/vista/package-info.java, srcalc/src/main/java/gov/va/med/srcalc/vista/vistalink/VistaLinkAuthenticator.java, srcalc/src/main/java/gov/va/med/srcalc/vista/vistalink/VistaLinkProcedureCaller.java, srcalc/src/main/webapp/WEB-INF/applicationContext.xml, srcalc/src/test/java/gov/va/med/srcalc/vista/RpcVistaPatientDaoTest.java, srcalc/src/test/java/gov/va/med/srcalc/vista/vistalink/MockVistaLinkConnection.java, srcalc/src/test/java/gov/va/med/srcalc/vista/vistalink/VistaLinkProcedureCallerTest.java, srcalc/src/test/resources/test-context.xml
Improve in-source documentation, particularly with respect to VistA integration and security design.
=> Documentation improvements
